spring:
  application:
    name: swarm-orchestrator
  threads:
    virtual:
      enabled: true

  ai:
    mcp:
      client:
        stdio:
          connections:
            billing:
              command: java
              args: 
                - "-jar"
                - "../billing-mcp-server/target/billing-mcp-server-0.0.1-SNAPSHOT.jar"
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          enabled: true
          options:
            model: gemini-flash-latest
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        enabled: false
      embedding:
        enabled: true
        options:
          model: text-embedding-004



  datasource:
    url: jdbc:h2:mem:swarmdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

server:
  port: 8080
